services:
  db:
    image: mysql:8.0
    container_name: patiss-db
    environment:
      MYSQL_DATABASE: projet_patisserie3
      MYSQL_ROOT_PASSWORD: ""    # <-- mot de passe vide
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build:
      context: ./backend/pat3
      dockerfile: Dockerfile
    container_name: patiss-backend
    depends_on:
      - db
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/projet_patisserie3?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""   # <-- vide
      FILE_UPLOAD_DIR: /data/uploads
    volumes:
      - ./backend/pat3/Uploads:/data/uploads

volumes:
  dbdata:
