apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: patiss
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: root
  MYSQL_PASSWORD: root

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: patiss
data:
  MYSQL_DB: projet_patisserie3
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/projet_patisserie3?serverTimezone=UTC
